Update publish.yml for the 1.21 update
KosmX/minecraftPlayerAnimator pull request #97
Opened 2024-08-02 10:13 UTC by ArduFish123

I updated the publish.yml github workflow for Minecraft 1.21.

2024-08-16 19:25 UTC, MagicalAlexey commented
Why not published mod and can you publish 1.20.6 more?

2024-08-19 17:53 UTC, KosmX requested changes

2024-08-19 17:53 UTC, KosmX commented on coreLib/src/main/java/dev/kosmx/playerAnim/core/data/AnimationFormat.java
> -    private final String extension;
This is not update publish.yml.

2024-08-19 18:04 UTC, closed without merging

2024-08-19 19:44 UTC, ArduFish123 commented on coreLib/src/main/java/dev/kosmx/playerAnim/core/data/AnimationFormat.java
> -    private final String extension;
I did not change that file

2024-08-19 19:44 UTC, ArduFish123 commented on coreLib/src/main/java/dev/kosmx/playerAnim/core/data/AnimationFormat.java
> -    private final String extension;
That's weird

2024-08-19 19:45 UTC, ArduFish123 commented on coreLib/src/main/java/dev/kosmx/playerAnim/core/data/AnimationFormat.java
> -    private final String extension;
Sorry

2024-08-19 19:46 UTC, ArduFish123 commented on coreLib/src/main/java/dev/kosmx/playerAnim/core/data/AnimationFormat.java
> -    private final String extension;
I did not change that file